language: python
cache: pip
python:
  - "3.7"

install:
  - make config

script:
  - make ut
  - make build
  - make dl_model
  - make e2e

notifications:
  email:
    on_success: never
    on_failure: change