language: python
cache: pip
python:
  - "3.7"
services:
  - docker

install:
  - make config

script:
  - make ut
  - make build
  - make dl_model
  - make e2e
  - make docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make publish;
    fi

notifications:
  email:
    on_success: never
    on_failure: change