version: "3.4"

services:
  recogn:
    image: emkor/recogn-img:x86-cpu-aio
    build:
      context: .
      dockerfile: Dockerfile
    command: recogn-img /src/yolov3.h5 /src/coco_classes.txt /image /result/results.json --box-threshold 0.4 --obj-threshold 0.5
    volumes:
      - ./image:/image:ro
      - ./result:/result
